version: "3"
services:
  nginx:
    depends_on:
      - frontend
      - users-service
      - notes-service
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  users-service:
    build:
      dockerfile: Dockerfile.dev
      context: "./users-service"
    volumes:
      - /app/node_modules
      - ./users-service:/app
    environment:
      MONGO_URI: "mongodb+srv://admin-user:password-user@cluster.mongodb.net/users?retryWrites=true&w=majority"
      JWT_SECRET: "Dilipcool"
      PORT: 8080
  notes-service:
    build:
      dockerfile: Dockerfile.dev
      context: "./notes-service"
    volumes:
      - /app/node_modules
      - ./notes-service:/app
    environment:
      MONGO_URI: "mongodb+srv://admin-user:password-user@cluster0.fwlinqy.mongodb.net/notes?retryWrites=true&w=majority"
      JWT_SECRET: "Dilipcool"
      PORT: 7070
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
