apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-service
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: notes-service
        image: sexareds/notes-service
        ports:
        - containerPort: 8080